import { Link } from 'react-router-dom';

const CONTENT = {
  contact: { title: 'Contact CaseVerse', intro: 'Need help with a cover, an order, or payment confirmation? Reach out with your order number when applicable.', items: [['Order help', 'Include your order number so the team can find the relevant details quickly.'], ['Product questions', 'Use the product model selector and product details first, then contact the team if you need help choosing a fit.'], ['Payment confirmation', 'For an eligible pending order, upload your eSewa proof from the order page. You can also request COD confirmation there.']] },
  faq: { title: 'Frequently asked questions', intro: 'Helpful answers about choosing, ordering, and confirming your CaseVerse cover.', items: [['Which iPhone models do you support?', 'Available models are shown on each product before you add it to cart. Choose the exact model for the best fit.'], ['How does the NPR 100 advance work?', 'After placing an order, pay the displayed advance with eSewa and upload a screenshot. Staff verify it before the order moves into processing.'], ['Can I request COD?', 'Yes. Select the WhatsApp COD option from an eligible pending order. It remains pending until staff confirm it.'], ['What if my proof is rejected?', 'You will see the reviewer note on your order and can upload a clearer proof while the order remains pending.'], ['How can I contact CaseVerse?', 'Use the contact options in the footer.']] },
  shipping: { title: 'Shipping & delivery', intro: 'CaseVerse uses the address supplied at checkout to arrange delivery.', items: [['Delivery details', 'Available delivery options and charges are shown during checkout before you place an order.'], ['Order tracking', 'Your account order history shows the latest order status once staff begin processing.']] },
  returns: { title: 'Returns & refunds', intro: 'If something is not right with your order, contact CaseVerse with your order number so the team can review it.', items: [['Before confirmation', 'Eligible pending orders can be cancelled from the order page before payment confirmation or processing.'], ['After delivery', 'Return or refund availability depends on the item condition and the order circumstances. Contact the team for current guidance.']] },
  terms: { title: 'Terms & conditions', intro: 'These store terms are a practical summary and can be updated as CaseVerse policies evolve.', items: [['Orders', 'Orders are subject to product availability and review of the checkout information provided.'], ['Payment confirmation', 'Advance-payment and COD confirmation requests are reviewed before fulfilment starts.'], ['Product information', 'Images and descriptions are presented to help you choose; select the exact device model before ordering.']] },
  privacy: { title: 'Privacy policy', intro: 'CaseVerse uses account, order, and delivery information to operate the store and support your order.', items: [['Information we use', 'We use the information you provide for account access, delivery, order support, and store operations.'], ['Payment proofs', 'Payment screenshots are stored privately and are available only to authorized staff reviewing the order.'], ['Your location', 'Checkout asks for your location only when you tap “Use my location”. Our server rounds it to about 100 metres and looks up the address with the OpenStreetMap Nominatim service. The position is not saved with your order or written to our logs, and you can always type your address instead.'], ['Place and address data', 'Address suggestions and place-name search use data © OpenStreetMap contributors, available under the Open Database License (openstreetmap.org/copyright).'], ['Questions', 'Contact CaseVerse if you need help with your account information or an order.']] },
};
export default function InfoPage({ type }) { const page = CONTENT[type] || CONTENT.faq; return <article className="info-page"><p className="eyebrow">CASEVERSE / CUSTOMER CARE</p><h1>{page.title}</h1><p className="muted info-intro">{page.intro}</p><div className="info-list">{page.items.map(([heading, body]) => <details key={heading}><summary>{heading}</summary><p>{body}</p></details>)}</div><Link className="btn subtle" to="/covers">Shop phone covers</Link></article>; }
